name: project_alpha
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0-35.0.dev <4.0.0"

dependencies:
  audioplayers: ^4.0.1
  dart_openai: ^1.9.1
  elevenlabs: ^1.0.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_dotenv: ^5.0.2
  flutter_sound: ^9.2.13
  just_audio: ^0.9.32
  mic_stream: ^0.6.5
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  supabase_flutter: ^1.7.0
  timeago: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
